stages:
  - test

runner_smoke_test:
  stage: test
  tags:
    - hil
  script:
    
    - cd src/ && cppcheck main.c
    - cd .. 
    - cd Drivers/ && make
    - cd .. && make
    - openocd -f interface/stlink.cfg -f target/stm32l1x_dual_bank.cfg -c "init; reset halt; flash write_image erase project.bin 0x8000000; reset; exit"
    - source /home/gitlab-runner/venv/bin/activate
    - robot pythonCode/robotSerial.robot
    #- st-flash --reset --connect-under-reset  write project.bin 0x8000000  #issue under Debian...
